### ISSUE TITLE
VERSION 5.0

### ISSUE THREAD

**Issue by jessesquires** [jessesquires/JSQMessagesViewController#172]
With [v4.0.0](https://github.com/jessesquires/MessagesTableViewController/releases) kicked off as the last stable release for iOS 6, it's now time to begin v5.0.0.

I have better-organized the issues here on GitHub, and plan to keep everyone informed of the plans for v5.0.0 in this thread. If you have any questions, comments, or suggestions, please leave them below.

**All work on version 5.0.0 will happen on branch `version_5_release` exclusively.** Please feel free to checkout this branch periodically to see my progress or even submit bug fixes!
## Version 5.0.0

**iOS support changes**
- [x] Drop iOS 6 support, become iOS 7+ only
- [x] Remove all iOS 6 assets
- [x] Strip all iOS 6-specific code

**Refactoring / Structural changes**
- [x] Convert from `UITableView` to `UICollectionView`
- [x] Use Storyboards and Auto-layout
- [x] Default to iOS 7 appearance and style
- [x] New `UICollectionViewCell` prototypes that match iOS 7
- [x] Re-implement `JSMessagesViewDelegate` as more proper design pattern
- [x] Re-implement `JSMessageViewDataSource` as more proper design pattern
- [x] Re-implement `JSMessageInputView` to be a `UIToolbar` subclass
- [x] Change class prefixes to `JSQ` to better prevent conflicts
- [x] ~~Rename repo to `JSQMessagesViewController`~~ See #258 

**New features**
- [x] Make `JSMessageInputView` more customizable with `leftBarButton` and `rightBarButton` properties
- [x] ~~Image messages, modular enough so consumers can load asynchronously if desired~~ _not for 5.0_
- [x] Add `UIDynamics` for "bouncy" messages
- [x] Toggle showing a "typing indicator bubble"
- [x] Toggle showing a "Load earlier messages" header
- [x] ~~Localization?~~ _not for 5.0, do as needed_ see #237

**Maintenance**
- [x] NSAsserts where appropriate
- [x] Better demo project
- [x] Close as many existing issues as possible (bugs & feature requests)

**Documentation**
- [x] Categories
- [x] Controllers
- [x] Factories
- [x] Layout
- [x] Model
- [x] Views

**Unit Tests**
- [x] Categories
- [x] Controllers
- [x] Factories
- [x] Layout
- [x] Model
- [x] Views

**Nice to have / Future work**
- [x] Landscape mode
- [x] ~~Instead of image messages, more general "media" messages~~ _not for 5.0_ see #223
- [x] ~~Infinite scrolling pagination~~ _not for 5.0_ see #236
- [x] ~~iOS 7 swipe-to-show-timestamps~~ _not for 5.0_ see #138 
- [x] Tap avatar delegate
- [x] ~~Edit mode for deleting messages~~ _not for 5.0_ see #235
## iOS 6 suport branch

As noted above, I will no longer be supporting iOS 6. (And you shouldn't either! As of this writing, iOS 7 adoption rates [are estimated at 80%](http://www.macrumors.com/2014/01/27/ios-7-adoption-80/).) Please note, because of the changes listed above, v4.0 and v5.0 will be entirely incompatible.

However, some may wish to continue supporting iOS 6. For this reason, I've created the branch [iOS6_support_stable](https://github.com/jessesquires/MessagesTableViewController/tree/iOS6_support_stable). I will not be contributing to this branch myself, but I will continue to accept pull requests.
