### ISSUE TITLE
[8.0] Message cells refactor / redesign

### ISSUE THREAD

**Issue by jessesquires** [jessesquires/JSQMessagesViewController#1720]
⚠️ Depends on finishing #453 first

For 8.0 release:
##### Goals:
- Improve and refine cell APIs and layout
- Better support for custom cells
##### Todo:
- [ ] Dedicated cell factory class for generating cells
- [ ] Provide a configuration to map cell classes and identifiers
- [ ] Remove the `cellTopLabel`, `cellBottomLabel`, etc. `8.0` will be moving to a **section-based** layout. This means each cell will be in its own section, thus each cell can have it's own headers and footers.
- [ ] Remove some existing hacks that make media cells work

**Comment by jessesquires** [comment]
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq
