### ISSUE TITLE
Support dynamic type

### ISSUE THREAD

**Issue by jessesquires** [jessesquires/JSQMessagesViewController#497]
Library should support dynamic type for message text and cell labels. It should also support runtime switching. For example: `[UIFont preferredFontForTextStyle: ...]`.

**TODO:**
- [x] implement dynamic type for message text bubbles (fixed in 71c21c06bf5325386653d2c3f4da31f2c537facd)
- [x] implement dynamic type for cell labels (`cellTopLabel`, `messageBubbleTopLabel`, `cellBottomLabel`)
- [ ] implement dynamic type for inputToolbar
- [x] implement runtime switching

**NOTES:**
1. investigate using `systemLayoutSizeFittingSize:`, `intrinsicContentSize`, etc. either instead of or in support of the string calculations that occur in `messageBubbleSizeForItemAtIndexPath:`
2. Supporting dynamic type for the cell labels may require that we calculate the height of these labels automatically, instead of via delegate methods (actually, this is probably better for the library as a whole).
3. As in (2), supporting dynamic type for the inputToolbar will require updating the default toolbar height constraint based on the font size.

**Comment by esilverberg** [comment]
Hi,

I have a pull request that brings dynamic type support to the input toolbar.

https://github.com/jessesquires/JSQMessagesViewController/pull/1169

Cheers,
-Eric

**Comment by jessesquires** [comment]
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq
